steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: sh
    args: ['load_images.sh']
  - name: 'debian:10'
    args: ['tar', 'zxfv', 'imgs.tgz']
  - name: 'python:3'
    args: ['python', 'scripts/download_image.py', 'arm', '--site', 'wiki']
  - name: 'debian:10'
    args: ['tar', 'zcvf', 'imgs.tgz', 'imgs']
  - name: 'debian:10'
    args: ['tar', 'zxfv', 'charaimgs.tgz']
  - name: 'python:3'
    args: ['python', 'scripts/download_image.py', 'chara', '--site', 'wiki']
  - name: 'debian:10'
    args: ['tar', 'zcvf', 'charaimgs.tgz', 'charaimgs']
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: sh
    args: ['save_images.sh']
  - name: 'node:8'
    entrypoint: npm
    args: ['install']
  - name: 'node:8'
    entrypoint: npm
    args: ['run', 'production-build']
  # do not ignore dist directory
  - name: 'debian:10'
    args: ['sed', '-i', '-e', 's/^dist/# dist/', '.dockerignore']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.nginx', '-t', 'gcr.io/$PROJECT_ID/motocal:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/motocal:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'motocal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/motocal:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/motocal:$COMMIT_SHA'
