steps:
     - name: 'node:8'
       entrypoint: npm
       args: ['install']
     - name: 'node:8'
       entrypoint: npm
       args: ['run', 'production-build']
     # push the container image to Container Registry
     - name: 'gcr.io/cloud-builders/docker'
       args: ['push', 'gcr.io/$PROJECT_ID/motocal:$COMMIT_SHA']
